# ===================================================================
# Spring Boot configuration for the "env" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    datasource:
        url: jdbc:postgresql://FILL_HOST:FILL_PORT/FILL_DATABASE
        username: FILL_USER
        password: FILL_PASS
    jpa:
        show-sql: false
    mail:
        host: FILL_HOST
        port: FILL_PORT
        username: FILL_USER
        password: FILL_PASS

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://jhipster.github.io/common-application-properties/
# ===================================================================

jhipster:
    mail:
        from: FILL_EMAIL
        base-url: http://FILL_APPLICATION_URL

# ===================================================================
# Pentaho specific properties
# Add your own Pentaho properties here
# ===================================================================

pentaho:
    endpoint: FILL_PENTAHO_ENDPOINT # Required: Pentaho Data Integration Server Endpoint
    auth:
        user: FILL_PENTAHO_USER # Required: Pentaho Data Integration Server User
        password: FILL_PENTAHO_PASSWORD # Required: Pentaho Data Integration Server Password
    host:
        os: FILL_PENTAHO_HOST_OS # Required: Pentaho Host Operating System
        address: FILL_PENTAHO_HOST_ADDRESS # Required: Pentaho Host Address
        username: FILL_PENTAHO_HOST_USERNAME # Required: Pentaho Host Username
        password: FILL_PENTAHO_HOST_PASSWORD # Required: Pentaho Host Password
        sudoUsername: FILL_PENTAHO_HOST_SUDO_USERNAME # Required: Pentaho Host Sudo Username
        sudoPassword: FILL_PENTAHO_HOST_SUDO_PASSWORD # Required: Pentaho Host Sudo Password
        sudoPasswordPromptRegex: FILL_PENTAHO_HOST_SUDO_PASSWORD_PROMPT_REGEX # Required: Pentaho Host Sudo Password Prompt Regular Expression
        sftpPath: FILL_PENTAHO_HOST_SFTP_PATH # Required: Pentaho Host SFTP Path
        resourcesPath: FILL_PENTAHO_HOST_RESOURCES_PATH # Required: Pentaho Host Resources Path
        ownerUserResourcesPath: FILL_PENTAHO_HOST_OWNER_USER_RESOURCES_PATH # Required: Pentaho Host Owner User Resources Path
        ownerGroupResourcesPath: FILL_PENTAHO_HOST_OWNER_GROUP_RESOURCES_PATH # Required: Pentaho Host Owner Group Resources Path
        mainResourcePrefix: FILL_KEY_PENTAHO_MAIN_RESOURCE_PREFIX # Required: Pentaho main resources prefix
git:
    username: FILL_WITH_GIT_USER # Required: GIT owner username for access
    password: FILL_WITH_GIT_PASSWORD # Required: GIT owner password for access
    branch: FILL_WITH_BRANCH # Required: GIT ETL branch for ETL execution

# ===================================================================
# AES Encript specific properties
# Add your own aes properties here
# ===================================================================
aes:
    secretKeySalt: FILL_SECRET_KEY_SALT # Required: Pentaho Host Owner User Resources Path
    secretKeyPassword: FILL_SECRET_KEY_PASSWORD # Required: For example application name COETL_GOBCAN

# ===================================================================
# Application specific properties
# Add your own application properties here.
# ===================================================================

application:
    cas:
        endpoint: FILL_CAS_ENDPOINT # Required: Cas Endpoint
        service: FILL_SERVICE_URL # Required: Aplication service
        login:  # Optional: Only change if needed (Leave empty for cas.enpoint + '/login')
        logout: # Optional: Only change if needed(Leave empty for cas.enpoint + '/logout')
    installation:
        type: FILL_INSTALLATION_TYPE # Required: Installation Type Context (EXTERNAL / INTERNAL)
    enviroment: FILL_WITH_ENVIROMENT_NAME # Use value PRODUCTION to disable enviroment info in the email error subject

# ===================================================================
# Application debug properties
#
# Uncomment if debug mode needed
# ===================================================================

# debug
