version: '2'
services:
    coetl-app:
        image: coetl
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://coetl-postgresql:5432/coetl
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    coetl-postgresql:
        extends:
            file: postgresql.yml
            service: coetl-postgresql
