-- Crea un usuario y se le asigna un rol existente
-- Los usuarios de tipo admin en la columna 'RELLENAR_NOMBRE_ORGANISMO_EXISTENTE' deberá ser nulo
SELECT add_usuario_with_existing_rol('RELLENAR_USUARIO_LDAP', 'RELLENAR_NOMBRE_USUARIO', 'RELLENAR_PRIMER_APPELLIDO_USUARIO', 'RELLENAR_SEGUNDO_APPELLIDO_USUARIO', 'RELLENAR_CORREO_ELECTRONICO_USUARIO', 'RELLENAR_NOMBRE_ROL_EXISTENTE', 'RELLENAR_NOMBRE_ORGANISMO_EXISTENTE');
